import { Request, Response } from "express";
import { z } from "zod";
import { Order, OrderState } from "../models/Order";
import { Rider } from "../models/Rider";
import { AppError } from "../middleware/errorHandler";
import { applyTransition } from "./orderController";
import { assignNearestRider } from "../services/matchingService";
import { recordAuditAction } from "../services/auditService";
import { notify } from "../services/notificationService";
import { emitToRecipient } from "../services/socketRegistry";
import { telegramService } from "../services/telegramService";

const riderNext: Record<string, OrderState> = { RIDER_ASSIGNED:"RIDER_ACCEPTED", RIDER_ACCEPTED:"RIDER_ARRIVING", RIDER_ARRIVING:"RIDER_AT_PICKUP", RIDER_AT_PICKUP:"PICKUP_OTP_PENDING", PICKED_UP:"IN_TRANSIT", IN_TRANSIT:"RIDER_AT_DESTINATION", RIDER_AT_DESTINATION:"DELIVERY_OTP_PENDING" };
export async function dispatchOrder(req:Request,res:Response){ const order=await Order.findById(req.params.id); if(!order)throw new AppError("Order not found.",404); if(order.status!=="SEARCHING_RIDER")throw new AppError("Order is not searching for a rider.",409); if(!order.pickup)throw new AppError("Order pickup details are missing.",409); const rider=await assignNearestRider(String(order._id)); if(!rider)throw new AppError("No eligible rider is currently online.",409); await recordAuditAction({actorType:"ADMIN",actorId:req.auth!.sub,action:"RIDER_AUTO_ASSIGNED",targetType:"Order",targetId:String(order._id),after:{riderId:String(rider._id)}}); await notify({recipientType:"RIDER",recipientId:String(rider._id),type:"ORDER_ASSIGNED",title:"New delivery assigned",body:`Order ${order.publicId} is ready for pickup at ${order.pickup.fullAddress}.`,relatedType:"Order",relatedId:String(order._id)}); telegramService.events.orderStatusChanged({orderPublicId:order.publicId,status:"RIDER_ASSIGNED",actor:"ADMIN",detail:`Rider ${rider.publicId} assigned`}); emitToRecipient("USER",String(order.customerId),"order:status-changed",{orderId:String(order._id),status:"RIDER_ASSIGNED"}); res.json({order:await Order.findById(order._id),rider}); }
export async function advanceOrder(req:Request,res:Response){ const order=await Order.findById(req.params.id); if(!order)throw new AppError("Order not found.",404); if(String(order.riderId)!==req.auth!.sub)throw new AppError("Not found.",404); const next=riderNext[order.status]; if(!next)throw new AppError("This order is waiting for an OTP/payment/admin action.",409); applyTransition(order.status as OrderState,next); order.status=next; order.statusHistory.push({status:next}); await order.save(); emitToRecipient("USER",String(order.customerId),"order:status-changed",{orderId:String(order._id),status:next}); res.json({order}); }
export async function riderRejectAssignment(req:Request,res:Response){ const body=z.object({reason:z.string().optional()}).parse(req.body); const order=await Order.findById(req.params.id); if(!order||String(order.riderId)!==req.auth!.sub)throw new AppError("Not found.",404); if(order.status!=="RIDER_ASSIGNED")throw new AppError("Assignment cannot be rejected now.",409); order.riderId=undefined; applyTransition(order.status as OrderState,"SEARCHING_RIDER"); order.status="SEARCHING_RIDER"; order.statusHistory.push({status:"SEARCHING_RIDER",note:body.reason??"Rider declined assignment."}); await order.save(); const rider=await Rider.findById(req.auth!.sub); if(rider){rider.cancellationCount+=1;await rider.save();} res.json({order}); }
