import { Request, Response } from "express";
import { z } from "zod";
import { User } from "../models/User";
import { Order } from "../models/Order";
import { Rider } from "../models/Rider";
import { Rating } from "../models/Rating";
import { Dispute } from "../models/Dispute";
import { AppError } from "../middleware/errorHandler";
import { recordAuditAction } from "../services/auditService";
import { notify } from "../services/notificationService";
import { telegramService } from "../services/telegramService";
export async function savedAddresses(req: Request, res: Response) { const user = await User.findById(req.auth!.sub); if (!user) throw new AppError("User not found.",404); if (req.method === "GET") return res.json({ addresses: user.savedAddresses }); const body=z.object({ label:z.enum(["HOME","WORK","OTHER"]), customLabel:z.string().optional(), address:z.string(), landmark:z.string().optional(), lat:z.number().optional(), lng:z.number().optional() }).parse(req.body); user.savedAddresses.push(body); await user.save(); res.status(201).json({ addresses:user.savedAddresses }); }
export async function deleteSavedAddress(req: Request,res:Response){ const user=await User.findById(req.auth!.sub); if(!user) throw new AppError("User not found.",404); const item=user.savedAddresses.id(req.params.id!); if(!item) throw new AppError("Address not found.",404); item.deleteOne(); await user.save(); res.json({addresses:user.savedAddresses}); }
export async function rateOrder(req: Request,res: Response){ const b=z.object({rating:z.number().int().min(1).max(5),comment:z.string().max(500).optional()}).parse(req.body); const order=await Order.findById(req.params.id); if(!order || String(order.customerId)!==req.auth!.sub || order.status!=="DELIVERED" || !order.riderId) throw new AppError("Order cannot be rated.",400); if(await Rating.exists({orderId:order._id})) throw new AppError("This order has already been rated.",409); const rating=await Rating.create({orderId:order._id,customerId:req.auth!.sub,riderId:order.riderId,rating:b.rating,comment:b.comment}); const rider=await Rider.findById(order.riderId); if(rider){ const count=Math.max(1,rider.completedDeliveries); rider.rating=Math.round(((rider.rating*(count-1))+b.rating)/count*100)/100; await rider.save(); await notify({recipientType:"RIDER",recipientId:String(rider._id),type:"RATING_RECEIVED",title:"You received a new rating",body:`${b.rating}/5 for order ${order.publicId}${b.comment?`: "${b.comment}"`:"."}`,relatedType:"Order",relatedId:String(order._id)}); telegramService.events.ratingReceived({orderPublicId:order.publicId,riderName:rider.fullName,rating:b.rating,comment:b.comment}); } order.ratedByCustomer=true; await order.save(); res.status(201).json({rating}); }
export async function disputeOrder(req: Request,res: Response){ const b=z.object({reason:z.string().min(5).max(1000),category:z.enum(["DAMAGED_ITEM","LATE_DELIVERY","WRONG_ITEM","PAYMENT_ISSUE","RIDER_CONDUCT","OTHER"]).default("OTHER")}).parse(req.body); const order=await Order.findById(req.params.id); if(!order || String(order.customerId)!==req.auth!.sub) throw new AppError("Order not found.",404); if(order.status!=="DELIVERED" && order.status!=="IN_TRANSIT" && order.status!=="DELIVERY_OTP_PENDING") throw new AppError("This order cannot be disputed at its current stage.",400); order.status="DISPUTED"; order.statusHistory.push({status:"DISPUTED",note:b.reason}); await order.save(); const dispute=await Dispute.create({orderId:order._id,customerId:req.auth!.sub,riderId:order.riderId,reason:b.reason,category:b.category}); await recordAuditAction({actorType:"CUSTOMER",actorId:req.auth!.sub,action:"ORDER_DISPUTED",targetType:"Order",targetId:String(order._id),reason:b.reason}); telegramService.events.newDispute({orderPublicId:order.publicId,type:b.category}); res.status(201).json({order,dispute}); }
export async function myDisputes(req: Request,res: Response){ const disputes=await Dispute.find({customerId:req.auth!.sub}).sort({createdAt:-1}); res.json({disputes}); }
export async function referral(req: Request,res:Response){ const user=await User.findById(req.auth!.sub); if(!user) throw new AppError("User not found.",404); if(!user.referralCode){ user.referralCode=`NG${String(user._id).slice(-6).toUpperCase()}`; await user.save(); } res.json({referralCode:user.referralCode}); }
